<!DOCTYPE html>
<html>
<head>
    <title>Communauté du Chemin Neuf</title>
    <meta property="og:title" content="Communauté du Chemin Neuf">
    <meta property="Content-Type" content="text/html; charset=UTF-8">
    <?php

    $this->headLink()
        ->prependStylesheet("/components/twbs/bootstrap/dist/css/bootstrap.min.css")
        ->prependStylesheet("/theme/cte/css/cte.css");
    $this->headScript()
        ->appendFile("/components/jquery/jquery/jquery-1.11.1.min.js")
        ->appendFile("/components/twbs/bootstrap/dist/js/bootstrap.min.js");

    echo $this->headLink();
    ?>
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-md-12" style="margin-top: 30px">
            <div class="well">
                <?php echo $this->content ?>
                <div class='clearfix'></div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->headScript(); ?>

</body>
</html>